services:
  readmefy-app:
    build: ../readmefy-app
    container_name: readmefy-app
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ../readmefy-app:/readmefy-app
      - /readmefy-app/node_modules
    networks:
      - readmefy-network
    depends_on:
      readmefy-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  readmefy-api:
    build: ../readmefy-api
    container_name: readmefy-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ../readmefy-api:/readmefy-api
      - /readmefy-api/node_modules
    depends_on:
      readmefy-database:
        condition: service_healthy
    environment:
      - READMEFY_ENV=${READMEFY_ENV}
      - READMEFY_SECRET=${READMEFY_SECRET}
      - READMEFY_USER=${READMEFY_USER}
      - READMEFY_PASSWORD=${READMEFY_PASSWORD}
      - MYSQL_DATABASE=${READMEFY_DATABASE}
      - MYSQL_USER=${READMEFY_USER}
      - MYSQL_PASSWORD=${READMEFY_PASSWORD}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
    networks:
      - readmefy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  readmefy-proxy:
    build: ../readmefy-conf/proxy
    container_name: readmefy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../readmefy-conf/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      readmefy-app:
        condition: service_healthy
      readmefy-api:
        condition: service_healthy
    networks:
      - readmefy-network
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-H",
          "Host: readmefy.localhost",
          "http://localhost",
        ]
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 10s

  readmefy-database:
    build: ../readmefy-conf/database
    container_name: readmefy-database
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - readmefy-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${READMEFY_ROOT_PASSWORD}
      MYSQL_DATABASE: ${READMEFY_DATABASE}
      MYSQL_USER: ${READMEFY_USER}
      MYSQL_PASSWORD: ${READMEFY_PASSWORD}
    networks:
      - readmefy-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 60s
      timeout: 10s

volumes:
  readmefy-data:

networks:
  readmefy-network:
    driver: bridge
